'use strict';

module.exports = (toolbox) => {
  toolbox.installNest = async ({
    projectScope,
    projectName,
    projectLanguage,
    framework,
    appDir,
    assetsPath,
    pkgJson,
    envVars,
  }) => {
    const {
      system: { run },
      print: { success, muted },
      filesystem: { copyAsync },
    } = toolbox;

    const fullProjectName = projectScope
      ? `@${projectScope}/${projectName}`
      : projectName;

    muted('Installing Nest...');

    try {
      await run('npx @nestjs/cli@^9.0.0');

      await run(
        `nest new ${fullProjectName} --directory ${projectName} --skip-git --skip-install --package-manager npm`
      );

      await copyAsync(
        `${assetsPath}/${framework}/src/main.ts`,
        `${appDir}/src/main.ts`,
        { overwrite: true }
      );

      Object.assign(envVars, {
        HTTP: {
          PORT: 3000,
        },
      });

      Object.assign(pkgJson.dependencies, {
        helmet: '^6.0.1',
        compression: '^1.7.4',
      });

      if (projectLanguage === 'TS') {
        Object.assign(pkgJson.devDependencies, {
          '@types/compression': '^1.7.2',
          '@nestjs/config': '^2.3.1',
        });
      }

      Object.assign(pkgJson.scripts, {
        start: 'node -r dotenv/config ./node_modules/.bin/nest start',
      });

      await run(
        `echo "This is a sample project generated by @nestjs/cli. You can extend it using the same CLI. For information on commands run" "\`nest --help\`" > ./${projectName}/README.md`
      );
    } catch (err) {
      throw new Error(`An error has occurred while installing Nest: ${err}`);
    }

    success(
      'Nest installation completed successfully. Please wait for the other steps to be completed...'
    );
  };
};
