'use strict'

module.exports = (toolbox) => {
  toolbox.installNest = async ({ projectScope, projectName }) => {
    const {
      system: { run },
      print: { error, success, muted },
    } = toolbox

    muted('Installing Nest...')
    try {
      await run('npm install -g @nestjs/cli')
      if (projectScope) {
        await run(
          `nest new @${projectScope}/${projectName} --skip-git --package-manager npm`
        )
        await run(
          `mv @${projectScope}/${projectName} ./ && rm -d @${projectScope}`
        )
      } else {
        await run(`nest new ${projectName} --skip-git --package-manager npm`)
      }
      await run(`cd ./${projectName} && git init -b main`)
      await run(
        `echo "This is a sample project generated by @nestjs/cli. You can extend it using the same CLI. For information on commands run" "\`nest --help\`" > ./${projectName}/README.md`
      )
    } catch (err) {
      error(`An error has occurred while installing Nest: ${err}`)
      process.exit(1)
    }

    success('Nest installation completed successfully')
  }
}
